### ISSUE TITLE
More info in the README

### ISSUE THREAD

**Issue by philwhln** [cloudfoundry-incubator/docker_app_lifecycle#1]
I'm really curious what this is and I see that it's just been added to diego-release, but there's nothing in the Diego design docs that I can see.

**Comment by ematpl** [comment]
Hi, @philwhln,

Sorry for the extreme delay on responding to this issue. To answer your question, the launcher and the healthcheck binaries run as separate processes inside the docker container, and the builder runs in a preloaded rootfs (currently one of the CF stacks) when staging a docker container as a CF app. Do that and the updated [app lifecycle description](https://github.com/cloudfoundry-incubator/diego-design-notes#app-lifecycles) in the Diego design notes provide enough clarification?

Thanks,
Eric, for the CF Runtime Diego team

**Comment by philwhln** [comment]
Hi @ematpl,

Thanks for the extra info!

> binaries run as separate processes inside the docker container

Is this repo for actually working with _Docker containers_ running within a Diego Cell? Or do you mean Docker _images_ running as _Warden_ containers, which is what I understand Diego supports?

Cheers,
Phil

**Comment by ematpl** [comment]
Hi, Phil,

Yes, you're correct, these are binaries that run in the warden/garden container that uses the Docker image as the underlying rootfs.

**Comment by philwhln** [comment]
:+1:
