### ISSUE TITLE
Support v2 private docker registry?

### ISSUE THREAD

**Issue by libnux** [cloudfoundry-incubator/docker_app_lifecycle#4]
I'm setting up a v2 private docker registry. Seems that the builder only support v1 registry? 

Could you please confirm this? Thanks.

**Comment by hsiliev** [comment]
We're currently using v2 registry for the [docker cache](https://github.com/cloudfoundry-incubator/diego-docker-cache-release). Our [CI](https://diego.ci.cf-app.com/?groups=diego-docker-cache) runs fine against it, although it uses the v1 endpoint.

There is no support for insecure registries though. We expect this to be added by the end of the year.

Seems you have a specific scenario that is failing right now. Can you please elaborate on it?

**Comment by libnux** [comment]
Hi @hsiliev,

BTW, I setup my V2 docker registry following this guide: [https://github.com/docker/distribution/blob/master/docs/deploying.md] (https://github.com/docker/distribution/blob/master/docs/deploying.md)

The original issue was related to "insecure registry". I added "-insecureDockerRegistry" flag to the stager job, but it still did not work. The reason should be "There is no support for insecure registries though" as you said.

Then I secured my registry with my certificate issued by CA, and verified that it worked using local docker command. 
However, I still got below error when trying to staging my docker application:

---
Creating container
Successfully created container
Staging...
Staging process started ...
Staging process failed: Exit trace for group:
**builder exited with error: failed to fetch metadata from [docker.xxx.xxx.xx:5000/diego-docker] with tag [latest] and insecure registries [] due to HTTP code: 404**
Exit status 2
Staging Failed: Exited with status 2

---

I viewed the code of the builder command, and it seems that it always fetches the metadata from the /v1/xxxx endpoint of the registry, which does not exist in my private registry. 

Please help. Thanks.

**Comment by libnux** [comment]
I installed the v1 private registry, and now it works now. 

So v2 private registry is not supported for now? Thanks.

**Comment by ematpl** [comment]
Hi, @libnux,

Yes, it turns out the version of the docker code we were using in the docker app lifecycle's staging process was old enough that it didn't support v2 registries. We're fixing that in https://www.pivotaltracker.com/story/show/105158076, which should make it into a new final release of Diego soon.

Thanks,
Eric, CF Runtime Diego PM

**Comment by ematpl** [comment]
The changes to support v2 registries are in diego-release v0.1439.0, which is recommended for use with CF v223.
