### ISSUE TITLE
Is private registry protected with credentials supported? 

### ISSUE THREAD

**Issue by libnux** [cloudfoundry-incubator/docker_app_lifecycle#5]
I setup a private v1 docker registry with authentication enabled using nginx proxy, and tried to push a docker application in diego. But it failed to stage: 

---
Staging...
Staging process started ...
Staging process failed: Exit trace for group:
builder exited with error: failed to fetch metadata from [docker.mi-ae.com.cn/diego] with tag [latest] and insecure registries [] due to Authentication is required.
Exit status 2
Staging Failed: Exited with status 2

---

Actually, I already specified the docker username and password when creating the app:
<code><pre>
cf curl /v2/apps -X POST -d '{
  "name": "dockertest",
  "memory":512,
  "instances":1,
  "disk_quota":1024,
  "space_guid":"79f86aed-b38a-4de7-98c6-c25471c2abb7",
  "docker_image":"docker.xxxx.xxx.xx/diego",
  "docker_credentials_json":{
    "docker_user":"libnux",
    "docker_password":"password",
    "docker_email":"libnux@gmail.com"
  },
  "diego": true
}'
</pre></code>

**Comment by libnux** [comment]
BTW, no problem using docker client to push/run an image against my registry. I can login successfully.

**Comment by hsiliev** [comment]
Can you please try to specify your login server? You can do this by specifying `docker_login_server` in your request:
```
cf curl /v2/apps -X POST -d '{
  "name": "dockertest",
  "memory":512,
  "instances":1,
  "disk_quota":1024,
  "space_guid":"79f86aed-b38a-4de7-98c6-c25471c2abb7",
  "docker_image":"docker.xxxx.xxx.xx/diego",
  "docker_credentials_json":{
    "docker_user":"libnux",
    "docker_password":"password",
    "docker_email":"libnux@gmail.com",
    "docker_login_server":"<your login server here>"
  },
  "diego": true
}'
```

I guess your login server should be the same as the one specified in the logs above (docker.mi-ae.com.cn/diego) unless you have some custom setup.

**Comment by libnux** [comment]
Thanks, @hsiliev. But the staging still failed.

I found that, to let docker do login, I've to set the DIEGO_DOCKER_CACHE env to true. If not, I got the "Authentication is required" error.

After I set this env varaiable to true, the staging process still failed as show below.

Could please help? 

Actually I do not need to cache the image to the same docker registry, is it possible to enable docker login without setting DIEGO_DOCKER_CACHE? 

Thanks.


Error message:
---
Pulling docker image docker.xxx.xxx.xx/diego:latest ...
Pulling repository docker.xxx.xxx.xx/diego
b5f75b6c4fa3: Pulling image (latest) from docker.xxx.xxx.xx/diego
b5f75b6c4fa3: Pulling image (latest) from docker.xxx.xxx.xx/diego, endpoint: https://docker.xxx.xxx.xx/v1/
b5f75b6c4fa3: Pulling dependent layers
cf2616975b4a: Pulling metadata
cf2616975b4a: Pulling fs layer
cf2616975b4a: Download complete
47f0a47155d5: Pulling metadata
47f0a47155d5: Pulling fs layer
47f0a47155d5: Download complete
32e97f5f5d6b: Pulling metadata
32e97f5f5d6b: Pulling fs layer
32e97f5f5d6b: Download complete
246659bee8aa: Pulling metadata
246659bee8aa: Pulling fs layer
246659bee8aa: Download complete
6eca2cb72610: Pulling metadata
6eca2cb72610: Pulling fs layer
6eca2cb72610: Download complete
b5f75b6c4fa3: Pulling metadata
b5f75b6c4fa3: Pulling fs layer
b5f75b6c4fa3: Download complete
b5f75b6c4fa3: Download complete
Status: Downloaded newer image for docker.xxx.xxx.xx/diego:latest
Docker image pulled.
Docker image will be cached as docker.xxx.xxx.xx:443/c10bc7c6-807f-45b7-6a82-8105f6b65b50
Tagging docker image docker.xxx.xxx.xx/diego:latest as docker.xxx.xxx.xx:443/c10bc7c6-807f-45b7-6a82-8105f6b65b50 ...
Docker image tagged.
Pushing docker image docker.xxx.xxx.xx:443/c10bc7c6-807f-45b7-6a82-8105f6b65b50
The push refers to a repository [docker.xxx.xxx.xx:443/c10bc7c6-807f-45b7-6a82-8105f6b65b50] (len: 1)
Sending image list
Authentication is required.
Please login prior to push:
**Username: EOF**
**failed to cache image docker.xxx.xxx.xx/diego:latest exit status 1**

---

**Comment by hsiliev** [comment]
Unfortunately you can only do this using the cache. There is a story to support private images without the cache: https://www.pivotaltracker.com/story/show/95230604

Do you use the same registry for caching and for storing private images?

**Comment by libnux** [comment]
Yes, caching and storing is on the same registry. This kind of caching setup is not supported? 

As in my last post, the staging process already successfully logged in and pulled down the image from the registry. I don't understand why it failed when pushing back again.

**Comment by hsiliev** [comment]
We do not support credentials protected cache. We rely on network isolation and TLS to secure it since we regard it as internal CF component. Therefore we do not expect to need login for pushing images.

I believe that if you separate the cache and the private registry your scenario will be running fine. It is interesting if these two registries can be co-located to save space, but I haven't tried/searched if this is possible.

Sorry for the troubles, but the cache is pretty new (experimental if you wish) project and that's one of the reasons to have it in separate from Diego repo. The other reason is that we still don't have a full list with all the scenarios we want to support.

**Comment by libnux** [comment]
The situation and requirement is that 

“I have a private docker registry protected by basic authentication, and I want to deploy images from it into diego. It should work if I specify the username,password and login_server. This is not related to docker caching."

Could this be supported?

**Comment by ematpl** [comment]
Hi, @libnux,

We'd very much like for CF+Diego to support running private docker images without relaying them into the diego-docker-cache, but for this even to be feasible we require that Garden-Linux support running images that require credentials. We'll be exploring support for these use cases in the next few rounds of work on Diego and Garden-Linux.

Thanks,
Eric, CF Runtime Diego PM

**Comment by ematpl** [comment]
The feature request for running private Docker images without requiring the caching workflow is captured in the Diego tracker story at https://www.pivotaltracker.com/story/show/95230604. I'm going to close this issue out as a result.

**Comment by libnux** [comment]
@ematpl, is this feature done in recent diego release? 

I tried with diego v0.1441.0 and private v2 docker registry, and it did not work yet.

**Comment by ematpl** [comment]
Hi, @libnux,

No, this feature is unfortunately not done yet. The Diego and Garden teams are still investigating the best way to implement this correctly in a truly multi-tenant environment such as Cloud Foundry, but we expect to have a roadmap for this feature available soon. I would suggest you watch the [Diego](https://www.pivotaltracker.com/n/projects/1003146) and [Garden](https://www.pivotaltracker.com/n/projects/1158420) team trackers, as well as the [cf-dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/), for news about this.

Thanks,
Eric

**Comment by mirakl577** [comment]
Hello, could someone please give advise what is the best way to pull docker  images from ECR

I tried to run the following command:

cf push app1 -o 123456789123.dkr.ecr.us-east-1.amazonaws.com/app1:1

but I got the following error: 
 no basic auth credentials

But I made ecr login and it returned - login successfull, also I tried separate EC2 instance with IAM role attached which have all ECR resources allowed for it, but with no luck.
